2022-02-18 22:03:56,347 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 22:03:56,348 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x00000219121F1970>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:04:35,905 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 61042)  
2022-02-18 22:04:36,705 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645214675.9050555, 'user': {'account_name': ' Test0'}}  
2022-02-18 22:04:36,705 server.py  INFO       server               Клиент ('127.0.0.1', 61042) отключился от сервера.  
2022-02-18 22:09:41,380 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 61077)  
2022-02-18 22:09:42,181 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645214981.380393, 'user': {'account_name': ' Test'}}  
2022-02-18 22:09:42,182 server.py  INFO       server               Клиент ('127.0.0.1', 61077) отключился от сервера.  
2022-02-18 22:10:37,835 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 61085)  
2022-02-18 22:10:38,637 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215037.8359783, 'user': {'account_name': ' Test'}}  
2022-02-18 22:10:38,638 server.py  INFO       server               Клиент ('127.0.0.1', 61085) отключился от сервера.  
2022-02-18 22:10:52,536 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 22:10:52,538 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x000001CFDA172F70>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:11:02,948 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 61087)  
2022-02-18 22:11:03,748 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215062.9480305, 'user': {'account_name': 'Test'}} client=<socket.socket fd=412, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61087)>  
2022-02-18 22:11:03,748 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:11:03,748 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001CFDA172F70>, {'action': 'presence', 'time': 1645215062.9480305, 'user': {'account_name': 'Test'}}, <socket.socket fd=412, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61087)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:11:05,351 server.py  INFO       server               Клиент ('127.0.0.1', 61087) отключился от сервера.  
2022-02-18 22:12:14,230 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 22:12:14,232 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x00000252E0D1B1C0>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:12:14,235 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 61095)  
2022-02-18 22:12:14,239 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 61096)  
2022-02-18 22:12:14,240 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215134.2350936, 'user': {'account_name': 'test2'}} client=<socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61095)>  
2022-02-18 22:12:14,240 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:12:14,241 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x00000252E0D1B1C0>, {'action': 'presence', 'time': 1645215134.2350936, 'user': {'account_name': 'test2'}}, <socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61095)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:12:14,241 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 61097)  
2022-02-18 22:12:14,242 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215134.239083, 'user': {'account_name': 'test3'}} client=<socket.socket fd=420, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61096)>  
2022-02-18 22:12:14,242 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:12:14,243 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x00000252E0D1B1C0>, {'action': 'presence', 'time': 1645215134.239083, 'user': {'account_name': 'test3'}}, <socket.socket fd=420, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61096)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:12:14,244 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215134.239083, 'user': {'account_name': 'test1'}} client=<socket.socket fd=436, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61097)>  
2022-02-18 22:12:14,244 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:12:14,245 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x00000252E0D1B1C0>, {'action': 'presence', 'time': 1645215134.239083, 'user': {'account_name': 'test1'}}, <socket.socket fd=436, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 61097)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:12:15,845 server.py  INFO       server               Клиент ('127.0.0.1', 61095) отключился от сервера.  
2022-02-18 22:12:15,846 server.py  INFO       server               Клиент ('127.0.0.1', 61096) отключился от сервера.  
2022-02-18 22:12:15,848 server.py  INFO       server               Клиент ('127.0.0.1', 61097) отключился от сервера.  
2022-02-18 22:15:11,411 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 22:15:11,412 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x000001173CDC2F70>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:15:23,448 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 57440)  
2022-02-18 22:15:24,249 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215323.4475951, 'user': {'account_name': 'Test'}} client=<socket.socket fd=396, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57440)>  
2022-02-18 22:15:24,250 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:15:24,253 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001173CDC2F70>, {'action': 'presence', 'time': 1645215323.4475951, 'user': {'account_name': 'Test'}}, <socket.socket fd=396, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57440)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:15:25,854 server.py  INFO       server               Клиент ('127.0.0.1', 57440) отключился от сервера.  
2022-02-18 22:22:04,450 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 57484)  
2022-02-18 22:22:05,251 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215724.450734, 'user': {'account_name': 'test'}} client=<socket.socket fd=372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57484)>  
2022-02-18 22:22:05,251 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:22:05,255 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001173CDC2F70>, {'action': 'presence', 'time': 1645215724.450734, 'user': {'account_name': 'test'}}, <socket.socket fd=372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57484)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:22:06,856 server.py  INFO       server               Клиент ('127.0.0.1', 57484) отключился от сервера.  
2022-02-18 22:23:16,839 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 57489)  
2022-02-18 22:23:17,640 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215796.8386755, 'user': {'account_name': 'test'}} client=<socket.socket fd=400, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57489)>  
2022-02-18 22:23:17,640 server.py  WARNING    server               Проверка сообщения в check_message не успешна, ответ: Имя пользователя уже занято   
2022-02-18 22:23:17,643 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001173CDC2F70>, {'action': 'presence', 'time': 1645215796.8386755, 'user': {'account_name': 'test'}}, <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:26:30,402 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 22:26:30,404 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x000001720310B1C0>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:26:30,411 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 57506)  
2022-02-18 22:26:30,418 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 57507)  
2022-02-18 22:26:30,419 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215990.41176, 'user': {'account_name': 'test1'}} client=<socket.socket fd=448, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57506)>  
2022-02-18 22:26:30,419 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:26:30,420 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001720310B1C0>, {'action': 'presence', 'time': 1645215990.41176, 'user': {'account_name': 'test1'}}, <socket.socket fd=448, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57506)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:26:30,423 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 57508)  
2022-02-18 22:26:30,423 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215990.4187415, 'user': {'account_name': 'test3'}} client=<socket.socket fd=440, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57507)>  
2022-02-18 22:26:30,423 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:26:30,424 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001720310B1C0>, {'action': 'presence', 'time': 1645215990.4187415, 'user': {'account_name': 'test3'}}, <socket.socket fd=440, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57507)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:26:31,224 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645215990.423728, 'user': {'account_name': 'test2'}} client=<socket.socket fd=376, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57508)>  
2022-02-18 22:26:31,225 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:26:31,230 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001720310B1C0>, {'action': 'presence', 'time': 1645215990.423728, 'user': {'account_name': 'test2'}}, <socket.socket fd=376, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 57508)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:26:32,032 server.py  INFO       server               Клиент ('127.0.0.1', 57506) отключился от сервера.  
2022-02-18 22:26:32,033 server.py  INFO       server               Клиент ('127.0.0.1', 57507) отключился от сервера.  
2022-02-18 22:26:32,836 server.py  INFO       server               Клиент ('127.0.0.1', 57508) отключился от сервера.  
2022-02-18 22:33:29,371 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 22:33:29,372 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x000001D2A9B40F70>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:33:38,989 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 60500)  
2022-02-18 22:33:39,789 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645216418.9894314, 'user': {'account_name': 'name'}} client=<socket.socket fd=348, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60500)>  
2022-02-18 22:33:39,790 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:33:39,793 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001D2A9B40F70>, {'action': 'presence', 'time': 1645216418.9894314, 'user': {'account_name': 'name'}}, <socket.socket fd=348, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60500)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:33:41,394 server.py  INFO       server               Клиент ('127.0.0.1', 60500) отключился от сервера.  
2022-02-18 22:34:50,441 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 60509)  
2022-02-18 22:34:51,242 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645216490.4418478, 'user': {'account_name': 'test'}} client=<socket.socket fd=400, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60509)>  
2022-02-18 22:34:51,242 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:34:51,245 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001D2A9B40F70>, {'action': 'presence', 'time': 1645216490.4418478, 'user': {'account_name': 'test'}}, <socket.socket fd=400, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60509)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:34:52,847 server.py  INFO       server               Клиент ('127.0.0.1', 60509) отключился от сервера.  
2022-02-18 22:38:29,932 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 60526)  
2022-02-18 22:38:30,734 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645216709.932801, 'user': {'account_name': 'on'}} client=<socket.socket fd=408, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60526)>  
2022-02-18 22:38:30,734 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:38:30,735 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001D2A9B40F70>, {'action': 'presence', 'time': 1645216709.932801, 'user': {'account_name': 'on'}}, <socket.socket fd=408, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60526)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:38:31,535 server.py  INFO       server               Клиент ('127.0.0.1', 60526) отключился от сервера.  
2022-02-18 22:40:24,127 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 22:40:24,129 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x000002BBAD780F70>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:40:30,992 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 60535)  
2022-02-18 22:40:31,793 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645216830.9926267, 'user': {'account_name': 'one'}} client=<socket.socket fd=324, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60535)>  
2022-02-18 22:40:31,793 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:40:31,796 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000002BBAD780F70>, {'action': 'presence', 'time': 1645216830.9926267, 'user': {'account_name': 'one'}}, <socket.socket fd=324, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60535)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:40:51,007 server.py  INFO       server               Получено сообщение {'action': 'message', 'from': 'one', 'to': 'test', 'time': 1645216850.9077444, 'mess_text': 'ghbdtn'} client=<socket.socket fd=324, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60535)>  
2022-02-18 22:40:51,007 server.py  INFO       server               Получено сообщение в clients_message_handling, проверка успешна  
2022-02-18 22:40:51,008 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000002BBAD780F70>, {'action': 'message', 'from': 'one', 'to': 'test', 'time': 1645216850.9077444, 'mess_text': 'ghbdtn'}, <socket.socket fd=324, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60535)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:40:51,008 server.py  ERROR      server               Пользователь test не зарегистрирован, отправка сообщения невозможна  
2022-02-18 22:40:51,009 server.py  DEBUG      server               Была вызвана функция message_handling c параметрами (<__main__.Server object at 0x000002BBAD780F70>, {'action': 'message', 'from': 'one', 'to': 'test', 'time': 1645216850.9077444, 'mess_text': 'ghbdtn'}, [<socket.socket fd=324, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60535)>]), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:41:10,220 server.py  INFO       server               Получено сообщение {'action': 'exit', 'time': 1645216869.4754088, 'account_name': 'one'} client=<socket.socket fd=324, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60535)>  
2022-02-18 22:41:10,221 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000002BBAD780F70>, {'action': 'exit', 'time': 1645216869.4754088, 'account_name': 'one'}, <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:42:50,675 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 22:42:50,677 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x000001F2C56CB1C0>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:42:50,684 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 60548)  
2022-02-18 22:42:50,693 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 60549)  
2022-02-18 22:42:50,693 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645216970.6847045, 'user': {'account_name': 'test1'}} client=<socket.socket fd=344, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60548)>  
2022-02-18 22:42:50,693 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:42:50,694 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F2C56CB1C0>, {'action': 'presence', 'time': 1645216970.6847045, 'user': {'account_name': 'test1'}}, <socket.socket fd=344, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60548)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:42:50,698 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 60550)  
2022-02-18 22:42:50,699 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645216970.69368, 'user': {'account_name': 'test2'}} client=<socket.socket fd=472, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60549)>  
2022-02-18 22:42:50,699 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:42:50,700 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F2C56CB1C0>, {'action': 'presence', 'time': 1645216970.69368, 'user': {'account_name': 'test2'}}, <socket.socket fd=472, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60549)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:42:51,500 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645216970.698667, 'user': {'account_name': 'test3'}} client=<socket.socket fd=456, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60550)>  
2022-02-18 22:42:51,500 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 22:42:51,502 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F2C56CB1C0>, {'action': 'presence', 'time': 1645216970.698667, 'user': {'account_name': 'test3'}}, <socket.socket fd=456, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60550)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:43:05,915 server.py  INFO       server               Получено сообщение {'action': 'message', 'from': 'test2', 'to': 'test1', 'time': 1645216985.2962096, 'mess_text': 'hello'} client=<socket.socket fd=472, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60549)>  
2022-02-18 22:43:05,916 server.py  INFO       server               Получено сообщение в clients_message_handling, проверка успешна  
2022-02-18 22:43:05,921 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F2C56CB1C0>, {'action': 'message', 'from': 'test2', 'to': 'test1', 'time': 1645216985.2962096, 'mess_text': 'hello'}, <socket.socket fd=472, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60549)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:43:05,923 server.py  INFO       server               Пользователю test1 отправлено сообщение от test2  
2022-02-18 22:43:05,927 server.py  DEBUG      server               Была вызвана функция message_handling c параметрами (<__main__.Server object at 0x000001F2C56CB1C0>, {'action': 'message', 'from': 'test2', 'to': 'test1', 'time': 1645216985.2962096, 'mess_text': 'hello'}, [<socket.socket fd=344, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60548)>, <socket.socket fd=472, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60549)>, <socket.socket fd=456, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60550)>]), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:43:32,348 server.py  INFO       server               Получено сообщение {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1645217012.1121557, 'mess_text': 'oho'} client=<socket.socket fd=344, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60548)>  
2022-02-18 22:43:32,348 server.py  INFO       server               Получено сообщение в clients_message_handling, проверка успешна  
2022-02-18 22:43:32,355 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F2C56CB1C0>, {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1645217012.1121557, 'mess_text': 'oho'}, <socket.socket fd=344, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60548)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:43:32,356 server.py  INFO       server               Пользователю test2 отправлено сообщение от test1  
2022-02-18 22:43:32,361 server.py  DEBUG      server               Была вызвана функция message_handling c параметрами (<__main__.Server object at 0x000001F2C56CB1C0>, {'action': 'message', 'from': 'test1', 'to': 'test2', 'time': 1645217012.1121557, 'mess_text': 'oho'}, [<socket.socket fd=344, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60548)>, <socket.socket fd=472, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60549)>, <socket.socket fd=456, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60550)>]), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:43:42,770 server.py  INFO       server               Клиент ('127.0.0.1', 60549) отключился от сервера.  
2022-02-18 22:43:47,574 server.py  INFO       server               Получено сообщение {'action': 'exit', 'time': 1645217027.4532914, 'account_name': 'test1'} client=<socket.socket fd=344, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 60548)>  
2022-02-18 22:43:47,577 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F2C56CB1C0>, {'action': 'exit', 'time': 1645217027.4532914, 'account_name': 'test1'}, <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 22:43:51,582 server.py  INFO       server               Клиент ('127.0.0.1', 60550) отключился от сервера.  
2022-02-18 22:55:12,056 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 22:55:12,057 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x0000028720611EB0>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:04:36,152 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 23:04:36,153 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x000001EBAAAD1580>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:29:54,710 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 23:29:54,712 server.py  DEBUG      server               Была вызвана функция socket_init c параметрами (<__main__.Server object at 0x000001F39F06B2E0>,), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:29:54,713 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 49828)  
2022-02-18 23:29:54,717 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 49829)  
2022-02-18 23:29:54,717 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645219794.7125642, 'user': {'account_name': 'test1'}} client=<socket.socket fd=316, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49828)>  
2022-02-18 23:29:54,717 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 23:29:54,719 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'presence', 'time': 1645219794.7125642, 'user': {'account_name': 'test1'}}, <socket.socket fd=316, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49828)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:29:54,722 server.py  INFO       server               Соединение установлено c ('127.0.0.1', 49830)  
2022-02-18 23:29:54,723 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645219794.7175505, 'user': {'account_name': 'test2'}} client=<socket.socket fd=428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49829)>  
2022-02-18 23:29:54,723 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 23:29:54,724 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'presence', 'time': 1645219794.7175505, 'user': {'account_name': 'test2'}}, <socket.socket fd=428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49829)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:29:55,524 server.py  INFO       server               Получено сообщение {'action': 'presence', 'time': 1645219794.7225373, 'user': {'account_name': 'test3'}} client=<socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49830)>  
2022-02-18 23:29:55,525 server.py  INFO       server               Проверка сообщения в clients_message_handling успешна, ответ: 200  
2022-02-18 23:29:55,529 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'presence', 'time': 1645219794.7225373, 'user': {'account_name': 'test3'}}, <socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49830)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:30:11,538 server.py  INFO       server               Получено сообщение {'action': 'message', 'from': 'test3', 'to': 'hello', 'time': 1645219810.9865932, 'mess_text': 'hello'} client=<socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49830)>  
2022-02-18 23:30:11,539 server.py  INFO       server               Получено сообщение в clients_message_handling, проверка успешна  
2022-02-18 23:30:11,545 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'message', 'from': 'test3', 'to': 'hello', 'time': 1645219810.9865932, 'mess_text': 'hello'}, <socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49830)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:30:11,547 server.py  ERROR      server               Пользователь hello не зарегистрирован, отправка сообщения невозможна  
2022-02-18 23:30:11,550 server.py  DEBUG      server               Была вызвана функция message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'message', 'from': 'test3', 'to': 'hello', 'time': 1645219810.9865932, 'mess_text': 'hello'}, [<socket.socket fd=316, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49828)>, <socket.socket fd=428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49829)>, <socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49830)>]), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:30:21,157 server.py  INFO       server               Получено сообщение {'action': 'message', 'from': 'test3', 'to': 'test2', 'time': 1645219820.7467165, 'mess_text': 'hello'} client=<socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49830)>  
2022-02-18 23:30:21,157 server.py  INFO       server               Получено сообщение в clients_message_handling, проверка успешна  
2022-02-18 23:30:21,163 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'message', 'from': 'test3', 'to': 'test2', 'time': 1645219820.7467165, 'mess_text': 'hello'}, <socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49830)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:30:21,164 server.py  INFO       server               Пользователю test2 отправлено сообщение от test3  
2022-02-18 23:30:21,168 server.py  DEBUG      server               Была вызвана функция message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'message', 'from': 'test3', 'to': 'test2', 'time': 1645219820.7467165, 'mess_text': 'hello'}, [<socket.socket fd=316, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49828)>, <socket.socket fd=428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49829)>, <socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49830)>]), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:30:49,185 server.py  INFO       server               Получено сообщение {'action': 'message', 'from': 'test2', 'to': 'test3', 'time': 1645219848.6822813, 'mess_text': 'wow@!!'} client=<socket.socket fd=428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49829)>  
2022-02-18 23:30:49,185 server.py  INFO       server               Получено сообщение в clients_message_handling, проверка успешна  
2022-02-18 23:30:49,190 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'message', 'from': 'test2', 'to': 'test3', 'time': 1645219848.6822813, 'mess_text': 'wow@!!'}, <socket.socket fd=428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49829)>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:30:49,191 server.py  INFO       server               Пользователю test3 отправлено сообщение от test2  
2022-02-18 23:30:49,195 server.py  DEBUG      server               Была вызвана функция message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'message', 'from': 'test2', 'to': 'test3', 'time': 1645219848.6822813, 'mess_text': 'wow@!!'}, [<socket.socket fd=316, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49828)>, <socket.socket fd=428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49829)>, <socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49830)>]), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:31:18,014 server.py  INFO       server               Получено сообщение {'action': 'exit', 'time': 1645219877.342943, 'account_name': 'test3'} client=<socket.socket fd=432, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49830)>  
2022-02-18 23:31:18,018 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'exit', 'time': 1645219877.342943, 'account_name': 'test3'}, <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:31:21,223 server.py  INFO       server               Получено сообщение {'action': 'exit', 'time': 1645219881.113845, 'account_name': 'test2'} client=<socket.socket fd=428, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49829)>  
2022-02-18 23:31:21,227 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'exit', 'time': 1645219881.113845, 'account_name': 'test2'}, <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:31:25,230 server.py  INFO       server               Получено сообщение {'action': 'exit', 'time': 1645219884.6949005, 'account_name': 'test1'} client=<socket.socket fd=316, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 49828)>  
2022-02-18 23:31:25,234 server.py  DEBUG      server               Была вызвана функция clients_message_handling c параметрами (<__main__.Server object at 0x000001F39F06B2E0>, {'action': 'exit', 'time': 1645219884.6949005, 'account_name': 'test1'}, <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции run  
2022-02-18 23:34:14,881 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
2022-02-18 23:35:29,610 server.py  DEBUG      server               Была вызвана функция arg_parser c параметрами (), {}.Вызов из модуля __main__.Вызов из функции main().Вызов из функции main  
